package com.example.spring.jwt;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class ApplicationTests {

	public static final String TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.Qo9q_QN40dUunJv-Cbos8mBm32ogd_kNOHpMiHR9p41xy_w9AuNf5CO7x2vGXo94jqFHboCpnpskcinY4uJFkmdgvVJgKgQWA0jVaftgFJKdW8edabPaANTAnCY1SLYDXnpje0bkL-5173JpqGdS5rbIxnr7BhZQgtoV1SYN6MnxY4UonjwoUePfUQTl1VqkCiOigNfafwCqNMBvbAd76CpkYI7Mh-w7kcbMOoNElv8Im3_xaBZ9fN75e2Q3zqiHwHsaP-ctXISQ5wCr30gw6D4qj6spk_8YQT0QvDsOUVKjIY48eHYArXDvqvZX7G9PKE3VB4-s5UeOZ6AWRajNVg";

	public static final String TOKEN_ERROR = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNTE2MjM5MDIyfQ.DZAl33G87q2j3jAWnZRi0zeOIJ5U50RVk6wFgSjCmfWZ-dVo2cO2SucwYeE4NXhHC9iiWkhaSRdJxKuCSbEdTVOb7EHKnKNWVcvWrB8OcVb2gPjfIz5SjgDrRGbLePW_2rUdGshO3DN5moet2jxibN-ngUmQMfLaBKjBpj36F3l9soxaVM_5D3LqvlQD_Kxi_TOOFPEP9UBQT5lzE5BTfcAmID_MubSxxNF3ByMpv6p2TZE4qmfdBmjIbE3sqiRyBY5v5sr94IYAlsygor0TxoBEoIkn6oUizu5UQCPb0MxdHmS0vq61d3m_ufCAYLowfiAQ877xY5Up9FJdqY3NHg";

	@Test
	public void contextLoads() {
	}

}
